# Generated by Django 6.0 on 2025-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_guest_address_guest_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ManyToManyField(related_name='bookings', to='hotel.guest'),
        ),
    ]
