# Generated by Django 6.0 on 2025-12-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_booking_guest_alter_guest_phone_booking_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='fan',
            field=models.BooleanField(default=False),
        ),
    ]
