# Generated by Django 6.0 on 2026-02-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_rename_booking_date_booking_reservation_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('reserved', 'Reserved')], default='active', max_length=20),
        ),
    ]
