# Generated by Django 6.0 on 2026-02-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('reserved', 'Reserved')], default='reservated', max_length=20),
        ),
    ]
